"""
conftest.py — root fixtures, config, and the screenshot/video/trace-on-failure
wiring into Allure. Generated by scaffold_generator.py — see
automation-standards.md's "Reporting" section for the contract this
implements. Do not hand-edit the failure-hook wiring without re-running the
scaffold's failure-evidence proof step.
"""

import pytest
from config.settings import settings


# ── Fresh reports per run: pytest.ini's --clean-alluredir wipes
#    reports/allure-results; this does the same for the readable evidence
#    archives so reports/ only ever holds the current run's files. Skipped on
#    xdist workers (they'd race and delete each other's evidence mid-run) and
#    when the user opted out with --no-clean-evidence.
def pytest_addoption(parser):
    parser.addoption(
        "--no-clean-evidence",
        action="store_true",
        default=False,
        help="keep reports/screenshots|videos|traces from previous runs instead of clearing them",
    )


def pytest_sessionstart(session):
    config = session.config
    if hasattr(config, "workerinput"):  # xdist worker — controller already cleaned
        return
    if config.getoption("--no-clean-evidence"):
        return
    from core.utils.reporting import clear_evidence_dirs
    clear_evidence_dirs(settings.reports_dir)


# ── Failure-hook wiring: stash the call-phase report on the item so fixture
#    teardown can decide whether to attach failure evidence. ──────────────
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    rep = outcome.get_result()
    setattr(item, f"rep_{rep.when}", rep)

    if rep.when == "call" and rep.failed:
        from core.utils.reporting import attach_screenshot, extract_test_case_id
        test_case_id = extract_test_case_id(item)
        page_fixture = item.funcargs.get("page")
        driver_fixture = item.funcargs.get("driver")
        try:
            if page_fixture is not None:
                attach_screenshot(page_fixture.screenshot(), test_case_id,
                                  settings.project_name, settings.reports_dir)
            elif driver_fixture is not None:
                attach_screenshot(driver_fixture.get_screenshot_as_png(), test_case_id,
                                  settings.project_name, settings.reports_dir)
        except Exception:  # noqa: BLE001 — never let evidence capture mask the real failure
            pass


@pytest.fixture(scope="session")
def playwright_instance():
    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def browser(playwright_instance):
    from core.web.browser import launch_browser
    b = launch_browser(playwright_instance)
    yield b
    b.close()


@pytest.fixture(scope="session")
def alt_engine_browser(playwright_instance):
    """Session-cached NON-default browser engines (firefox, msedge, webkit),
    launched lazily on first request and closed at session end.

    Added 2026-09-23 for PBI 131054's cross-browser keyboard-navigation
    cases (ADO-141813 Firefox, ADO-141832 Edge). Deliberately feeds the
    EXISTING `page` fixture through its param dict's "engine" key instead of
    introducing `firefox_page` / `edge_page` fixtures: conftest's
    `pytest_runtest_makereport` hook looks the browser page up by the
    literal funcarg name "page", so a differently-named fixture would
    silently lose its failure screenshot, video and trace.
    """
    from core.web.browser import launch_browser_for_engine

    cache = {}

    def _get(engine: str):
        if engine not in cache:
            cache[engine] = launch_browser_for_engine(playwright_instance, engine)
        return cache[engine]

    yield _get

    for b in cache.values():
        try:
            b.close()
        except Exception:  # noqa: BLE001 — teardown must never mask the real failure
            pass


@pytest.fixture
def page(request, browser, alt_engine_browser, tmp_path):
    from core.web.browser import new_context
    from core.utils.reporting import attach_trace, attach_video, extract_test_case_id

    param = getattr(request, "param", None)
    # Indirect-parametrization param is either:
    #   - a (width, height) tuple -> viewport override (existing usage), or
    #   - a dict {"viewport": (w, h), "locale": "ar-QA", "timezone_id": "Asia/Qatar",
    #     "auth": False}
    #     -> browser-locale cases (fresh Chrome/Safari with a given primary
    #     language, no prior cookie) that need a real Playwright-context
    #     locale rather than a second real browser.
    #     "auth": False opts OUT of the cached storageState auto-load — REQUIRED
    #     for tests whose subject is login/permissions (RBAC denial, TC-134658):
    #     with the default, a cached admin session would pre-authenticate the
    #     context and invalidate (or false-PASS) the permission assertion.
    #     "engine": "firefox" | "msedge" | "webkit"
    #     -> run this ONE test on a real second browser engine (PBI 131054's
    #     cross-browser keyboard-navigation cases). Omitted/"chromium" keeps
    #     the session-scoped default browser, so nothing else changes.
    if isinstance(param, dict):
        viewport = param.get("viewport")
        locale = param.get("locale")
        timezone_id = param.get("timezone_id")
        use_auth_state = param.get("auth", True)
        engine = param.get("engine", "chromium")
    else:
        viewport = param
        locale = None
        timezone_id = None
        use_auth_state = True
        engine = "chromium"
    active_browser = browser if engine == "chromium" else alt_engine_browser(engine)
    video_dir = str(tmp_path / "videos")
    context = new_context(
        active_browser,
        viewport=viewport,
        record_video_dir=video_dir,
        locale=locale,
        timezone_id=timezone_id,
        use_auth_state=use_auth_state,
    )
    pg = context.new_page()
    yield pg

    failed = getattr(request.node, "rep_call", None) is not None and request.node.rep_call.failed
    test_case_id = extract_test_case_id(request.node)
    trace_path = tmp_path / "trace.zip"

    # video_path/tracing.stop()/context.close() were previously unguarded:
    # any one of them throwing (e.g. a page/context left in a bad state by a
    # test that failed mid-navigation, such as a throttled-network timeout)
    # aborted this whole teardown block BEFORE the attach_video/attach_trace
    # calls below ever ran — silently costing a failing test ALL of its
    # evidence (no screenshot beyond the makereport hook's own best-effort
    # attempt, no video, no trace), with nothing surfaced to explain why.
    # Each step is now isolated so one capture failing doesn't take the
    # others down with it.
    video_path = None
    try:
        video_path = pg.video.path() if pg.video else None
    except Exception:  # noqa: BLE001 — evidence capture must never mask the real failure
        pass

    try:
        if failed:
            context.tracing.stop(path=str(trace_path))
        else:
            context.tracing.stop()
    except Exception:  # noqa: BLE001
        pass

    try:
        context.close()  # Playwright only finalizes the video file once the context closes
    except Exception:  # noqa: BLE001
        pass

    if failed and video_path:
        try:
            attach_video(video_path, test_case_id, settings.project_name, ext="webm",
                         reports_dir=settings.reports_dir)
        except Exception:  # noqa: BLE001
            pass
    if failed and trace_path.exists():
        try:
            attach_trace(str(trace_path), test_case_id, settings.project_name,
                         reports_dir=settings.reports_dir)
        except Exception:  # noqa: BLE001
            pass


# ── Browserless HTTP fixtures (Playwright APIRequestContext) ─────────────
#    Added 2026-09-23 for the PBI 131053 sitemap.xml batch. Protocol-level
#    cases (HTTP status / content-type / XML well-formedness) need no DOM, so
#    they use these instead of the `page` fixture — no browser is launched.
#
#    FUNCTION-scoped on purpose, never session-scoped: an APIRequestContext
#    keeps cookies across the requests it makes, so a shared one would carry
#    a JSESSIONID picked up by an earlier test into a later "anonymous
#    visitor / crawler" test and quietly invalidate its logged-out premise.
@pytest.fixture
def api_context_factory(playwright_instance):
    """Creates anonymous APIRequestContexts (no storageState) on demand and
    disposes every one of them at teardown. Use it when a test needs a
    non-default User-Agent or headers; otherwise use `api_request_context`."""
    from core.web.browser import new_api_context

    created = []

    def _make(user_agent: str = None, extra_http_headers: dict = None, timeout: int = None):
        ctx = new_api_context(
            playwright_instance,
            user_agent=user_agent,
            extra_http_headers=extra_http_headers,
            timeout=timeout,
        )
        created.append(ctx)
        return ctx

    yield _make

    for ctx in created:
        try:
            ctx.dispose()
        except Exception:  # noqa: BLE001 — teardown must never mask the real failure
            pass


@pytest.fixture
def api_request_context(api_context_factory):
    """A fresh, anonymous APIRequestContext with Playwright's default UA."""
    return api_context_factory()
