"""
conftest.py — root fixtures, config, and the screenshot/video/trace-on-failure
wiring into Allure. Generated by scaffold_generator.py — see
automation-standards.md's "Reporting" section for the contract this
implements. Do not hand-edit the failure-hook wiring without re-running the
scaffold's failure-evidence proof step.
"""

import pytest
from config.settings import settings


# ── Fresh reports per run: pytest.ini's --clean-alluredir wipes
#    reports/allure-results; this does the same for the readable evidence
#    archives so reports/ only ever holds the current run's files. Skipped on
#    xdist workers (they'd race and delete each other's evidence mid-run) and
#    when the user opted out with --no-clean-evidence.
def pytest_addoption(parser):
    parser.addoption(
        "--no-clean-evidence",
        action="store_true",
        default=False,
        help="keep reports/screenshots|videos|traces from previous runs instead of clearing them",
    )


def pytest_sessionstart(session):
    config = session.config
    if hasattr(config, "workerinput"):  # xdist worker — controller already cleaned
        return
    if config.getoption("--no-clean-evidence"):
        return
    from core.utils.reporting import clear_evidence_dirs
    clear_evidence_dirs(settings.reports_dir)


# ── Failure-hook wiring: stash the call-phase report on the item so fixture
#    teardown can decide whether to attach failure evidence. ──────────────
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    rep = outcome.get_result()
    setattr(item, f"rep_{rep.when}", rep)

    if rep.when == "call" and rep.failed:
        from core.utils.reporting import attach_screenshot, extract_test_case_id
        test_case_id = extract_test_case_id(item)
        page_fixture = item.funcargs.get("page")
        driver_fixture = item.funcargs.get("driver")
        try:
            if page_fixture is not None:
                attach_screenshot(page_fixture.screenshot(), test_case_id,
                                  settings.project_name, settings.reports_dir)
            elif driver_fixture is not None:
                attach_screenshot(driver_fixture.get_screenshot_as_png(), test_case_id,
                                  settings.project_name, settings.reports_dir)
        except Exception:  # noqa: BLE001 — never let evidence capture mask the real failure
            pass


@pytest.fixture(scope="session")
def playwright_instance():
    from playwright.sync_api import sync_playwright
    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def browser(playwright_instance):
    from core.web.browser import launch_browser
    b = launch_browser(playwright_instance)
    yield b
    b.close()


@pytest.fixture
def page(request, browser, tmp_path):
    from core.web.browser import new_context
    from core.utils.reporting import attach_trace, attach_video, extract_test_case_id

    param = getattr(request, "param", None)
    # Indirect-parametrization param is either:
    #   - a (width, height) tuple -> viewport override (existing usage), or
    #   - a dict {"viewport": (w, h), "locale": "ar-QA", "timezone_id": "Asia/Qatar",
    #     "auth": False}
    #     -> browser-locale cases (fresh Chrome/Safari with a given primary
    #     language, no prior cookie) that need a real Playwright-context
    #     locale rather than a second real browser.
    #     "auth": False opts OUT of the cached storageState auto-load — REQUIRED
    #     for tests whose subject is login/permissions (RBAC denial, TC-134658):
    #     with the default, a cached admin session would pre-authenticate the
    #     context and invalidate (or false-PASS) the permission assertion.
    if isinstance(param, dict):
        viewport = param.get("viewport")
        locale = param.get("locale")
        timezone_id = param.get("timezone_id")
        use_auth_state = param.get("auth", True)
    else:
        viewport = param
        locale = None
        timezone_id = None
        use_auth_state = True
    video_dir = str(tmp_path / "videos")
    context = new_context(
        browser,
        viewport=viewport,
        record_video_dir=video_dir,
        locale=locale,
        timezone_id=timezone_id,
        use_auth_state=use_auth_state,
    )
    pg = context.new_page()
    yield pg

    failed = getattr(request.node, "rep_call", None) is not None and request.node.rep_call.failed
    test_case_id = extract_test_case_id(request.node)
    video_path = pg.video.path() if pg.video else None
    trace_path = tmp_path / "trace.zip"
    if failed:
        context.tracing.stop(path=str(trace_path))
    else:
        context.tracing.stop()
    context.close()  # Playwright only finalizes the video file once the context closes
    if failed and video_path:
        attach_video(video_path, test_case_id, settings.project_name, ext="webm",
                     reports_dir=settings.reports_dir)
    if failed and trace_path.exists():
        attach_trace(str(trace_path), test_case_id, settings.project_name,
                     reports_dir=settings.reports_dir)
